### ISSUE TITLE
Observed v/s predicted density plot

### ISSUE THREAD

**Issue by abhi8893** [anu-coder/Boston-House-Price-Prediction_case_study#1]
Maybe look into developing a general function for plotting observed v/s predicted density?
https://github.com/anu-coder/Boston-House-Price-Prediction_case_study/blob/c61663bda63fd38e6d43412fe0794f9ede3a93ed/Notebooks/BostonHousingPrediction_Notebook2.Rmd#L159-L165

You can format the function as below 
```r
dens.compare.plot <- function(obs, pred){
    # Your code here
    # Auto title, xlab, ylab and legend
}
```

**Comment by anu-coder** [comment]
![Issue1_BHPP](https://user-images.githubusercontent.com/58327314/80956899-c052be80-8e1f-11ea-95bb-c772e46b4eb2.PNG)
Hi, Have a look into the image here, if you are willing to fix this issue do also incorporate codes to "re-margin" so that none of the plots goes out of the plot margin.

**Comment by anu-coder** [comment]
Hi there, @abhi8893 , I have created an R package, in the repository R_utils which does the above job. Now, can you just help me out a bit so as to, incorporate proper margin, so that one does not face a margin conflict while plotting?
